/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HTMLViewer.java
 *
 * Created on 20.12.2012, 8:35:00
 */
package app;

import ts3000.model.Document;

/**
 *
 * @author Андрей
 */
public class HTMLViewer extends javax.swing.JPanel {

    /** Creates new form HTMLViewer */
    public HTMLViewer() {
        initComponents();
        this.viewer.setContentType("text/html");
        this.viewer.setText("");
        this.viewer.setEditable(false);
    }
    
    public void setText(String text) {
        this.viewer.setText(text);
    }
    
    public void loadDocument(Document doc) {
        this.viewer.setText(doc.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        viewer = new javax.swing.JEditorPane();

        scrollPanel.setViewportView(viewer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JEditorPane viewer;
    // End of variables declaration//GEN-END:variables
}
