/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResultField.java
 *
 * Created on 05.12.2012, 7:12:33
 */
package app;

import java.util.ArrayList;
import java.util.Arrays;
import ts3000.model.Document;

/**
 *
 * @author Андрей
 */
public class SearchResultField extends javax.swing.JPanel {

    /** Creates new form SearchResultField */
    public SearchResultField() {
        initComponents();
    }
    
    private ArrayList<Document> docs = new ArrayList<Document>(10);
    
    private int pages = 0;
    private int currentPage;
    
    private void makeVisibleByPage(int pageNum) {
        if (pageNum < pages - 1) {
            makeVisibleByNum(4);
        } else {
            int howMuch = docs.size() % 4;
            if (howMuch == 0 && pages > 0) {
                howMuch = 4;
            }
            makeVisibleByNum(howMuch);
        }   
    }
    
    private void makeVisibleByNum(int num) {
        searchResult1.setVisible(num >= 1);
        searchResult2.setVisible(num >= 2);
        searchResult3.setVisible(num >= 3);
        searchResult4.setVisible(num >= 4);        
    }
    
    public boolean setPage(int newPage) {
        if (pages < newPage || newPage < 0) {
            return false;
        } else {
            currentPage = newPage;
            lblCurPage.setText("Page " + Integer.toString(currentPage + 1));
            makeVisibleByPage(newPage);
            int howMuch = docs.size() % 4;
            if (howMuch == 0 || newPage < pages - 1) {
                howMuch = 4;
            }
            
            if (pages == 0) {
                return true;
            }
            
            if (howMuch >= 1) {
                searchResult1.setCaption(docs.get(newPage*4 + 0).getTitle());
                String desc = docs.get(newPage*4 + 0).getAnnotation();
                if (desc.length() >= 50) {
                    desc = desc.substring(0, 50) + "...";
                }
                searchResult1.setDescription(desc);
                searchResult1.setPath(docs.get(newPage*4 + 0).getTitle() + "/");
            }
            if (howMuch >= 2) {
                searchResult2.setCaption(docs.get(newPage*4 + 1).getTitle());
                String desc = docs.get(newPage*4 + 1).getAnnotation();
                if (desc.length() >= 50) {
                    desc = desc.substring(0, 50) + "...";
                }
                searchResult2.setDescription(desc);
                searchResult2.setPath(docs.get(newPage*4 + 1).getTitle() + "/");
            }
            if (howMuch >= 3) {
                searchResult3.setCaption(docs.get(newPage*4 + 2).getTitle());
                String desc = docs.get(newPage*4 + 2).getAnnotation();
                if (desc.length() >= 50) {
                    desc = desc.substring(0, 50) + "...";
                }
                searchResult3.setDescription(desc);
                searchResult3.setPath(docs.get(newPage*4 + 2).getTitle() + "/");
            }
            if (howMuch >= 4) {
                searchResult4.setCaption(docs.get(newPage*4 + 3).getTitle());
                String desc = docs.get(newPage*4 + 3).getAnnotation();
                if (desc.length() >= 50) {
                    desc = desc.substring(0, 50) + "...";
                }
                searchResult4.setDescription(desc);
                searchResult4.setPath(docs.get(newPage*4 + 3).getTitle() + "/");
            }
            
            return true;
        }
    }
    
    public void setSource(Document[] docs) {
        this.docs = new ArrayList<Document>(docs.length);
        this.docs.addAll(Arrays.asList(docs));
        pages = (docs.length + 3)/4;
        setPage(0);
    }
    
    public void setSize(int i) {
        this.setSize(300, i*120 + 100);
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchResult1 = new app.SearchResult();
        searchResult2 = new app.SearchResult();
        searchResult3 = new app.SearchResult();
        searchResult4 = new app.SearchResult();
        cmbSortBy = new javax.swing.JComboBox();
        lblSortBy = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lnkPrevPage = new javax.swing.JLabel();
        lnkNextPage = new javax.swing.JLabel();
        lblCurPage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        cmbSortBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "name ascending", "name descending", "date" }));

        lblSortBy.setText("sort by:");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24));
        lblTitle.setText("Search results");

        lnkPrevPage.setText("<<");
        lnkPrevPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lnkPrevPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnkPrevPageMouseClicked(evt);
            }
        });

        lnkNextPage.setText(">>");
        lnkNextPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lnkNextPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnkNextPageMouseClicked(evt);
            }
        });

        lblCurPage.setText("curr");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                .addComponent(lblSortBy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchResult2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(searchResult3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(searchResult4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(searchResult1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(lnkPrevPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnkNextPage)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle)
                    .addComponent(lblSortBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchResult1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResult2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResult3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchResult4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurPage)
                    .addComponent(lnkNextPage)
                    .addComponent(lnkPrevPage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lnkPrevPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnkPrevPageMouseClicked
        if (currentPage == 0)
            return;
        
        setPage(currentPage - 1);
    }//GEN-LAST:event_lnkPrevPageMouseClicked

    private void lnkNextPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnkNextPageMouseClicked
        if (currentPage == pages - 1)
            return;
        
        setPage(currentPage + 1);
    }//GEN-LAST:event_lnkNextPageMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox cmbSortBy;
    protected javax.swing.JLabel lblCurPage;
    protected javax.swing.JLabel lblSortBy;
    protected javax.swing.JLabel lblTitle;
    protected javax.swing.JLabel lnkNextPage;
    protected javax.swing.JLabel lnkPrevPage;
    protected app.SearchResult searchResult1;
    protected app.SearchResult searchResult2;
    protected app.SearchResult searchResult3;
    protected app.SearchResult searchResult4;
    // End of variables declaration//GEN-END:variables
}
