/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchPanel.java
 *
 * Created on 17.12.2012, 5:23:53
 */
package app;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import ts3000.model.Category;
import ts3000.model.Document;

/**
 *
 * @author Андрей
 */
public class SearchPanel extends javax.swing.JPanel {

    /** Creates new form SearchPanel */
    public SearchPanel() {
        
            initComponents();
            
        try {    
            imgPicture = (Image) ImageIO.read(new File("swe.jpg"));
        } catch (IOException ex) {
            imgPicture = new BufferedImage(picWidth, picHeight, 0);
        }
    }
    
    protected int picWidth = 400;
    protected int picHeight = 200;
    
    protected Document[] gotDocs;
    protected MainWindow parentWindow;
    protected static Image imgPicture;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbxSearchField = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnLucky = new javax.swing.JButton();

        tbxSearchField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbxSearchField.setText("search documents...");
        tbxSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxSearchFieldActionPerformed(evt);
            }
        });
        tbxSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbxSearchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbxSearchFieldFocusLost(evt);
            }
        });
        tbxSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbxSearchFieldKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search!");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnLucky.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLucky.setText("Feeling lucky!");
        btnLucky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuckyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(btnLucky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(226, 226, 226))
                    .addComponent(tbxSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(tbxSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLucky, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbxSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxSearchFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tbxSearchFieldActionPerformed

    protected void loadDocs(String query) {
    	ArrayList<Document> result = parentWindow.database.proccessQuery(query);
    	gotDocs =  new Document[result.size()];
    	int iteration = 0;
    	for (Document doc : result) {
    		gotDocs[iteration++] = doc;
    	}
    }
    
    protected void setSearch(String searchedText) {
        loadDocs(searchedText);
        if (searchedText.length() >= 30) {
                    searchedText = searchedText.substring(0, 30) + "...";
                }
        parentWindow.searchResults.lblTitle.setText("Search results - \"" + searchedText + "\"");
        parentWindow.searchResults.lnkToCategories.setVisible(false);
        parentWindow.searchResults.setCompleteSorting();
        parentWindow.searchResults.setSource(gotDocs);
        parentWindow.setSearchResults();
    }
    
    @Override 
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(imgPicture, (this.getWidth() - imgPicture.getWidth(this)) / 2, 
                (tbxSearchField.getLocation().y - imgPicture.getHeight(this)) / 2, this);
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        setSearch(tbxSearchField.getText());
        parentWindow.searchField.setText(tbxSearchField.getText());
        parentWindow.searchField.requestFocus();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbxSearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxSearchFieldFocusGained
        if (tbxSearchField.getText().equals("search documents...")) {
            tbxSearchField.setText("");
        }
    }//GEN-LAST:event_tbxSearchFieldFocusGained

    private void tbxSearchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbxSearchFieldFocusLost
        if (tbxSearchField.getText().equals("")) {
            tbxSearchField.setText("search documents...");
        }
    }//GEN-LAST:event_tbxSearchFieldFocusLost

    private void tbxSearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxSearchFieldKeyTyped
        if (evt.getKeyChar() == 10 || evt.getKeyChar() == 13) {
            btnSearchActionPerformed(null);
        }
    }//GEN-LAST:event_tbxSearchFieldKeyTyped

    private void btnLuckyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuckyActionPerformed
        ArrayList<Category> categories = parentWindow.database.getCategories();
        Random rand = new Random(new Date().getTime());
        ArrayList<Document> docs = parentWindow.database.getDocsByCategory(categories.get(rand.nextInt(categories.size())).getName());
        Document doc = docs.get(rand.nextInt(docs.size()));
        parentWindow.viewerPanel.openedFrom = 2;
        parentWindow.viewerPanel.lnkBack.setText("<< back to the search");        
        parentWindow.viewerPanel.loadDocument(doc);
        parentWindow.setViewerPanel();
        parentWindow.searchPanel.btnLucky.requestFocus();
    }//GEN-LAST:event_btnLuckyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnLucky;
    protected javax.swing.JButton btnSearch;
    protected javax.swing.JTextField tbxSearchField;
    // End of variables declaration//GEN-END:variables
}
